import React, { createContext, useContext, useState, useCallback } from 'react';

export type Language = 'en' | 'ar' | 'sv';

export interface LanguageContextType {
  currentLanguage: Language;
  changeLanguage: (lang: Language) => void;
  isRTL: boolean;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// VibeMix Translations
const translations = {
  en: {
    'app.name': 'VibeMix',
    'app.tagline': 'Generate playlists that match your mood',
    'app.description': 'Discover music that perfectly captures how you feel. Select your mood, choose genres, and let VibeMix create the perfect soundtrack for your moment.',
  'nav.home': 'Home',
  'nav.discover': 'Discover',
  'nav.settings': 'Settings',
  'auth.login': 'Login',
  'auth.signup': 'Sign Up',
  'auth.welcome': 'Welcome to VibeMix',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.displayName': 'Display Name',
  'auth.username': 'Username',
  'auth.confirmPassword': 'Confirm Password',
  'auth.emailPlaceholder': 'Enter your email',
  'auth.passwordPlaceholder': 'Enter your password',
  'auth.displayNamePlaceholder': 'Your display name',
  'auth.usernamePlaceholder': 'Your username',
  'auth.confirmPasswordPlaceholder': 'Confirm your password',
  'auth.signingIn': 'Signing in...',
  'auth.creatingAccount': 'Creating account...',
  'auth.passwordMismatch': 'Passwords do not match',
  'auth.passwordTooShort': 'Password must be at least 6 characters',
  'auth.profile': 'Profile',
  'auth.myPlaylists': 'My Playlists',
  'auth.settings': 'Settings',
  'auth.signOut': 'Sign Out',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.system': 'System',
    'mood.happy': 'Happy',
    'mood.chill': 'Chill', 
    'mood.focus': 'Focus',
    'mood.sad': 'Sad',
    'mood.energetic': 'Energetic',
    'mood.romantic': 'Romantic',
    'mood.confident': 'Confident',
    'mood.mellow': 'Mellow',
    'mood.party': 'Party',
    'mood.rainy': 'Rainy Day',
    'mood.select': 'How are you feeling?',
    'genre.select': 'Choose your genres',
    'language.select': 'Select music languages',
    'button.getStarted': 'Get Started',
    'button.generatePlaylist': 'Generate Playlist',
    'button.connectSpotify': 'Connect Spotify',
    'hero.startJourney': 'Start Your Musical Journey',
    'hero.exploreMusic': 'Explore Music',
    'hero.tryDemo': 'Try Interactive Demo',
    'features.instantPlaylist': 'Instant Playlist Creation',
    'features.instantPlaylistDesc': 'Generate perfectly curated playlists in seconds. Just pick your mood, select genres, and let our AI do the magic.',
    'features.globalMusic': 'Global Music Discovery',
    'features.globalMusicDesc': 'Explore music from around the world in multiple languages. Discover your next favorite artist from any culture.',
    'features.joinThousands': 'Join thousands of music lovers who have already discovered their perfect soundtracks.',
    'features.startToday': 'Start your musical journey today!',
    'experience.title': 'Experience VibeMix',
    'experience.subtitle': 'Get a taste of what VibeMix can do. Explore trending genres or preview our curated music selection.',
    'howItWorks.title': 'How It Works',
    'howItWorks.subtitle': 'Creating your perfect playlist is just four simple steps away',
    'howItWorks.step1': 'Connect Spotify',
    'howItWorks.step1Desc': 'Link your Spotify account to access millions of songs and save your generated playlists directly to your music library.',
    'howItWorks.step2': 'Choose Your Mood',
    'howItWorks.step2Desc': 'Select from various moods like Happy, Chill, Energetic, or Romantic. Our AI understands the emotional context you\'re looking for.',
    'howItWorks.step3': 'Pick Genres & Language',
    'howItWorks.step3Desc': 'Customize your playlist by selecting genres you love and choose from multiple languages to discover global music.',
    'howItWorks.step4': 'Get Your Playlist',
    'howItWorks.step4Desc': 'Our intelligent algorithm instantly creates a personalized playlist that perfectly matches your mood and preferences.',
    'features.moodBased': 'Mood-Based',
    'features.moodBasedDesc': 'Select your current mood and let our algorithm find the perfect tracks that match your energy.',
    'features.multiGenre': 'Multi-Genre',
    'features.multiGenreDesc': 'Mix and match from multiple genres to create unique playlists that reflect your diverse taste.',
    'features.multiLanguage': 'Multi-Language',
    'features.multiLanguageDesc': 'Discover music in multiple languages and expand your musical horizons across cultures.',
    'discover.title': 'Create Your Perfect Playlist',
    'discover.subtitle': 'Tell us your mood, pick your genres, and let VibeMix craft a personalized musical journey just for you.',
    'discover.creatingVibe': 'Creating your vibe...',
    'discover.creating': 'Creating...',
    'discover.generate': 'Generate',
    'discover.readyGenerate': 'Ready to generate a',
    'discover.playlistWith': 'playlist with',
    'discover.music': 'music',
    'nav.myPlaylists': 'My Playlists',
  },
  ar: {
    'app.name': 'VibeMix',
    'app.tagline': 'أنشئ قوائم تشغيل تناسب مزاجك',
    'app.description': 'اكتشف الموسيقى التي تعكس مشاعرك بشكل مثالي. اختر مزاجك، حدد الأنواع الموسيقية، ودع VibeMix ينشئ الموسيقى التصويرية المثالية للحظتك.',
  'nav.home': 'الرئيسية',
  'nav.discover': 'اكتشف',
  'nav.settings': 'الإعدادات',
  'auth.login': 'تسجيل الدخول',
  'auth.signup': 'إنشاء حساب',
  'auth.welcome': 'مرحباً بك في VibeMix',
  'auth.email': 'البريد الإلكتروني',
  'auth.password': 'كلمة المرور',
  'auth.displayName': 'الاسم المعروض',
  'auth.username': 'اسم المستخدم',
  'auth.confirmPassword': 'تأكيد كلمة المرور',
  'auth.emailPlaceholder': 'أدخل بريدك الإلكتروني',
  'auth.passwordPlaceholder': 'أدخل كلمة المرور',
  'auth.displayNamePlaceholder': 'اسمك المعروض',
  'auth.usernamePlaceholder': 'اسم المستخدم',
  'auth.confirmPasswordPlaceholder': 'أكد كلمة المرور',
  'auth.signingIn': 'جاري تسجيل الدخول...',
  'auth.creatingAccount': 'جاري إنشاء الحساب...',
  'auth.passwordMismatch': 'كلمات المرور غير متطابقة',
  'auth.passwordTooShort': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
  'auth.profile': 'الملف الشخصي',
  'auth.myPlaylists': 'قوائم التشغيل الخاصة بي',
  'auth.settings': 'الإعدادات',
  'auth.signOut': 'تسجيل الخروج',
    'theme.light': 'فاتح',
    'theme.dark': 'داكن',
    'theme.system': 'النظام',
    'mood.happy': 'سعيد',
    'mood.chill': 'مسترخي',
    'mood.focus': 'تركيز',
    'mood.sad': 'حزين',
    'mood.energetic': 'نشيط',
    'mood.romantic': 'رومانسي',
    'mood.confident': 'واثق',
    'mood.mellow': 'هادئ',
    'mood.party': 'حفلة',
    'mood.rainy': 'يوم ممطر',
    'mood.select': 'كيف تشعر؟',
    'genre.select': 'اختر الأنواع الموسيقية',
    'language.select': 'اختر لغات الموسيقى',
    'button.getStarted': 'ابدأ الآن',
    'button.generatePlaylist': 'إنشاء قائمة التشغيل',
    'button.connectSpotify': 'ربط Spotify',
    'hero.startJourney': 'ابدأ رحلتك الموسيقية',
    'hero.exploreMusic': 'استكشف الموسيقى',
    'hero.tryDemo': 'جرب العرض التفاعلي',
    'features.instantPlaylist': 'إنشاء قوائم تشغيل فورية',
    'features.instantPlaylistDesc': 'أنشئ قوائم تشغيل منسقة بشكل مثالي في ثوانٍ. اختر مزاجك، حدد الأنواع الموسيقية، ودع الذكاء الاصطناعي يقوم بالسحر.',
    'features.globalMusic': 'اكتشاف الموسيقى العالمية',
    'features.globalMusicDesc': 'استكشف الموسيقى من جميع أنحاء العالم بلغات متعددة. اكتشف فنانك المفضل التالي من أي ثقافة.',
    'features.joinThousands': 'انضم إلى الآلاف من عشاق الموسيقى الذين اكتشفوا بالفعل الموسيقى التصويرية المثالية لهم.',
    'features.startToday': 'ابدأ رحلتك الموسيقية اليوم!',
    'experience.title': 'جرب VibeMix',
    'experience.subtitle': 'احصل على طعم لما يمكن أن يفعله VibeMix. استكشف الأنواع الرائجة أو اطلع على مجموعة الموسيقى المنسقة لدينا.',
    'howItWorks.title': 'كيف يعمل',
    'howItWorks.subtitle': 'إنشاء قائمة التشغيل المثالية الخاصة بك لا يتطلب سوى أربع خطوات بسيطة',
    'howItWorks.step1': 'ربط Spotify',
    'howItWorks.step1Desc': 'اربط حساب Spotify الخاص بك للوصول إلى ملايين الأغاني وحفظ قوائم التشغيل المُنشأة مباشرة في مكتبة الموسيقى الخاصة بك.',
    'howItWorks.step2': 'اختر مزاجك',
    'howItWorks.step2Desc': 'اختر من بين مزاجات مختلفة مثل سعيد، مسترخي، نشيط، أو رومانسي. يفهم الذكاء الاصطناعي السياق العاطفي الذي تبحث عنه.',
    'howItWorks.step3': 'اختر الأنواع واللغة',
    'howItWorks.step3Desc': 'خصص قائمة التشغيل الخاصة بك عن طريق اختيار الأنواع التي تحبها واختر من بين لغات متعددة لاكتشاف الموسيقى العالمية.',
    'howItWorks.step4': 'احصل على قائمة التشغيل',
    'howItWorks.step4Desc': 'خوارزميتنا الذكية تنشئ على الفور قائمة تشغيل شخصية تتطابق تماماً مع مزاجك وتفضيلاتك.',
    'features.moodBased': 'مبني على المزاج',
    'features.moodBasedDesc': 'اختر مزاجك الحالي ودع خوارزميتنا تجد المقاطع المثالية التي تتناسب مع طاقتك.',
    'features.multiGenre': 'متعدد الأنواع',
    'features.multiGenreDesc': 'امزج وطابق من أنواع متعددة لإنشاء قوائم تشغيل فريدة تعكس ذوقك المتنوع.',
    'features.multiLanguage': 'متعدد اللغات',
    'features.multiLanguageDesc': 'اكتشف الموسيقى بلغات متعددة ووسع آفاقك الموسيقية عبر الثقافات.',
    'discover.title': 'أنشئ قائمة التشغيل المثالية',
    'discover.subtitle': 'أخبرنا عن مزاجك، اختر أنواعك، ودع VibeMix ينشئ رحلة موسيقية شخصية لك فقط.',
    'discover.creatingVibe': 'إنشاء المزاج الخاص بك...',
    'discover.creating': 'إنشاء...',
    'discover.generate': 'إنشاء',
    'discover.readyGenerate': 'جاهز لإنشاء قائمة تشغيل',
    'discover.playlistWith': 'مع موسيقى',
    'discover.music': '',
    'nav.myPlaylists': 'قوائم التشغيل الخاصة بي',
  },
  sv: {
    'app.name': 'VibeMix',
    'app.tagline': 'Generera spellistor som matchar ditt humör',
    'app.description': 'Upptäck musik som perfekt fångar hur du känner dig. Välj ditt humör, välj genrer och låt VibeMix skapa det perfekta soundtracket för ditt ögonblick.',
  'nav.home': 'Hem',
  'nav.discover': 'Upptäck',
  'nav.settings': 'Inställningar',
  'auth.login': 'Logga in',
  'auth.signup': 'Registrera',
  'auth.welcome': 'Välkommen till VibeMix',
  'auth.email': 'E-post',
  'auth.password': 'Lösenord',
  'auth.displayName': 'Visningsnamn',
  'auth.username': 'Användarnamn',
  'auth.confirmPassword': 'Bekräfta lösenord',
  'auth.emailPlaceholder': 'Ange din e-post',
  'auth.passwordPlaceholder': 'Ange ditt lösenord',
  'auth.displayNamePlaceholder': 'Ditt visningsnamn',
  'auth.usernamePlaceholder': 'Ditt användarnamn',
  'auth.confirmPasswordPlaceholder': 'Bekräfta ditt lösenord',
  'auth.signingIn': 'Loggar in...',
  'auth.creatingAccount': 'Skapar konto...',
  'auth.passwordMismatch': 'Lösenorden matchar inte',
  'auth.passwordTooShort': 'Lösenordet måste vara minst 6 tecken',
  'auth.profile': 'Profil',
  'auth.myPlaylists': 'Mina spellistor',
  'auth.settings': 'Inställningar',
  'auth.signOut': 'Logga ut',
    'theme.light': 'Ljus',
    'theme.dark': 'Mörk',
    'theme.system': 'System',
    'mood.happy': 'Glad',
    'mood.chill': 'Chill',
    'mood.focus': 'Fokus',
    'mood.sad': 'Ledsen',
    'mood.energetic': 'Energisk',
    'mood.romantic': 'Romantisk',
    'mood.confident': 'Självsäker',
    'mood.mellow': 'Lugn',
    'mood.party': 'Fest',
    'mood.rainy': 'Regnig dag',
    'mood.select': 'Hur mår du?',
    'genre.select': 'Välj dina genrer',
    'language.select': 'Välj musikspråk',
    'button.getStarted': 'Kom igång',
    'button.generatePlaylist': 'Skapa spellista',
    'button.connectSpotify': 'Anslut Spotify',
    'hero.startJourney': 'Starta din musikaliska resa',
    'hero.exploreMusic': 'Utforska musik',
    'hero.tryDemo': 'Prova interaktiv demo',
    'features.instantPlaylist': 'Omedelbar spellisteskapande',
    'features.instantPlaylistDesc': 'Generera perfekt kuraterade spellistor på sekunder. Bara välj ditt humör, välj genrer och låt vår AI göra magin.',
    'features.globalMusic': 'Global musikupptäckt',
    'features.globalMusicDesc': 'Utforska musik från hela världen på flera språk. Upptäck din nästa favoritartist från vilken kultur som helst.',
    'features.joinThousands': 'Gå med tusentals musikälskare som redan har upptäckt sina perfekta soundtracks.',
    'features.startToday': 'Starta din musikaliska resa idag!',
    'experience.title': 'Upplev VibeMix',
    'experience.subtitle': 'Få en smak av vad VibeMix kan göra. Utforska trendande genrer eller förhandsgranska vårt kuraterade musikval.',
    'howItWorks.title': 'Hur det fungerar',
    'howItWorks.subtitle': 'Att skapa din perfekta spellista är bara fyra enkla steg bort',
    'howItWorks.step1': 'Anslut Spotify',
    'howItWorks.step1Desc': 'Länka ditt Spotify-konto för att komma åt miljontals låtar och spara dina genererade spellistor direkt till ditt musikbibliotek.',
    'howItWorks.step2': 'Välj ditt humör',
    'howItWorks.step2Desc': 'Välj från olika humör som Glad, Chill, Energisk eller Romantisk. Vår AI förstår det emotionella sammanhanget du letar efter.',
    'howItWorks.step3': 'Välj genrer och språk',
    'howItWorks.step3Desc': 'Anpassa din spellista genom att välja genrer du älskar och välj från flera språk för att upptäcka global musik.',
    'howItWorks.step4': 'Få din spellista',
    'howItWorks.step4Desc': 'Vår intelligenta algoritm skapar omedelbart en personlig spellista som perfekt matchar ditt humör och preferenser.',
    'features.moodBased': 'Humörbaserad',
    'features.moodBasedDesc': 'Välj ditt nuvarande humör och låt vår algoritm hitta de perfekta låtarna som matchar din energi.',
    'features.multiGenre': 'Flera genrer',
    'features.multiGenreDesc': 'Mixa och matcha från flera genrer för att skapa unika spellistor som återspeglar din mångfaldiga smak.',
    'features.multiLanguage': 'Flerspråkig',
    'features.multiLanguageDesc': 'Upptäck musik på flera språk och utvidga dina musikaliska horisonter över kulturer.',
    'discover.title': 'Skapa din perfekta spellista',
    'discover.subtitle': 'Berätta ditt humör, välj dina genrer och låt VibeMix skapa en personlig musikalisk resa just för dig.',
    'discover.creatingVibe': 'Skapar din vibe...',
    'discover.creating': 'Skapar...',
    'discover.generate': 'Generera',
    'discover.readyGenerate': 'Redo att skapa en',
    'discover.playlistWith': 'spellista med',
    'discover.music': 'musik',
    'nav.myPlaylists': 'Mina spellistor',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('en');

  const changeLanguage = useCallback((lang: Language) => {
    setCurrentLanguage(lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  }, []);

  const t = useCallback((key: string) => {
    return translations[currentLanguage]?.[key as keyof typeof translations['en']] || key;
  }, [currentLanguage]);

  const isRTL = currentLanguage === 'ar';

  const value: LanguageContextType = {
    currentLanguage,
    changeLanguage,
    isRTL,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}