import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { mood, genres, languages, userId } = await req.json();
    
    console.log('Generating playlist for:', { mood, genres, languages, userId });

    // Create Supabase client
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Get user's Spotify tokens
    const { data: userPrefs, error: prefsError } = await supabase
      .from('user_preferences')
      .select('spotify_access_token, spotify_refresh_token')
      .eq('user_id', userId)
      .single();

    if (prefsError || !userPrefs?.spotify_access_token) {
      console.error('No Spotify access token found:', prefsError);
      return new Response(
        JSON.stringify({ error: 'Spotify not connected. Please connect your Spotify account first.' }), 
        { 
          status: 400,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        }
      );
    }

    // Build search query based on mood and genres
    const genreQuery = genres.join(' OR genre:');
    const moodKeywords = getMoodKeywords(mood);
    const searchQuery = `genre:${genreQuery} ${moodKeywords}`;
    
    console.log('Spotify search query:', searchQuery);

    // Search for tracks on Spotify
    const spotifyResponse = await fetch(`https://api.spotify.com/v1/search?q=${encodeURIComponent(searchQuery)}&type=track&limit=30&market=US`, {
      headers: {
        'Authorization': `Bearer ${userPrefs.spotify_access_token}`,
        'Content-Type': 'application/json',
      },
    });

    if (!spotifyResponse.ok) {
      console.error('Spotify API error:', spotifyResponse.status, await spotifyResponse.text());
      return new Response(
        JSON.stringify({ error: 'Failed to search Spotify tracks' }), 
        { 
          status: 500,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        }
      );
    }

    const spotifyData = await spotifyResponse.json();
    const tracks = spotifyData.tracks?.items || [];
    
    if (tracks.length === 0) {
      return new Response(
        JSON.stringify({ error: 'No tracks found for your criteria. Try different genres or mood.' }), 
        { 
          status: 404,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        }
      );
    }

    // Filter and select best tracks (limit to 20)
    const selectedTracks = tracks
      .filter((track: any) => track.preview_url) // Only tracks with preview
      .slice(0, 20);

    // Create playlist name
    const playlistName = `${mood.charAt(0).toUpperCase() + mood.slice(1)} ${genres.slice(0, 2).join(' & ')} Mix`;
    const playlistDescription = `A ${mood} playlist featuring ${genres.join(', ')} music. Generated by VibeMix.`;

    // Create playlist in database
    const { data: playlist, error: playlistError } = await supabase
      .from('playlists')
      .insert({
        user_id: userId,
        title: playlistName,
        description: playlistDescription,
        is_public: false,
      })
      .select()
      .single();

    if (playlistError) {
      console.error('Error creating playlist:', playlistError);
      return new Response(
        JSON.stringify({ error: 'Failed to create playlist' }), 
        { 
          status: 500,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        }
      );
    }

    // Add tracks to playlist_songs table
    const playlistSongs = selectedTracks.map((track: any, index: number) => ({
      playlist_id: playlist.id,
      song_id: track.id, // Using Spotify ID as song_id for now
      position: index + 1,
    }));

    const { error: songsError } = await supabase
      .from('playlist_songs')
      .insert(playlistSongs);

    if (songsError) {
      console.error('Error adding songs to playlist:', songsError);
      // Don't fail the request, just log the error
    }

    console.log('Playlist created successfully:', playlist.id);

    return new Response(
      JSON.stringify({ 
        playlist: {
          id: playlist.id,
          title: playlist.title,
          description: playlist.description,
          track_count: selectedTracks.length,
          tracks: selectedTracks.map((track: any) => ({
            id: track.id,
            name: track.name,
            artist: track.artists[0]?.name,
            preview_url: track.preview_url,
            duration_ms: track.duration_ms,
          }))
        }
      }), 
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      }
    );

  } catch (error) {
    console.error('Error in generate-playlist function:', error);
    return new Response(
      JSON.stringify({ error: 'Internal server error' }), 
      { 
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      }
    );
  }
});

function getMoodKeywords(mood: string): string {
  const moodMap: { [key: string]: string } = {
    happy: 'upbeat energetic positive cheerful',
    sad: 'melancholic emotional slow ballad',
    energetic: 'high-energy dance workout pump-up',
    chill: 'relaxed ambient chill downtempo',
    romantic: 'love romantic slow intimate',
    focused: 'instrumental focus ambient electronic',
    party: 'party dance upbeat celebration',
    nostalgic: 'throwback classic vintage retro',
  };
  
  return moodMap[mood] || 'popular';
}