// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjdwjprbsduenqlcvxyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqZHdqcHJic2R1ZW5xbGN2eHlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4ODg5ODYsImV4cCI6MjA3NDQ2NDk4Nn0.Hci_-q_mAlw-_j5J1WceEOmk5NRyu8M0DUCKc61eM0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});